INSERT INTO regiones(region_id, nombre_region) VALUES (1,'sudamerica');
INSERT INTO regiones(region_id, nombre_region) VALUES (2,'centroAmerica');
INSERT INTO regiones(region_id, nombre_region) VALUES (3,'NorteAmerica');
INSERT INTO regiones(region_id, nombre_region) VALUES (4,'Europa');
INSERT INTO regiones(region_id, nombre_region) VALUES (5,'Asia');
INSERT INTO regiones(region_id, nombre_region) VALUES (6,'Africa');
INSERT INTO regiones(region_id, nombre_region) VALUES (7,'Oceania');
INSERT INTO regiones(region_id, nombre_region) VALUES (8,'Antartida');
INSERT INTO clientes (region_id,apellido,createAt,email,nombre) VALUES (2,'Perez', '2022-11-09 00:00:00', 'juan@unicauca.edu.co', 'Juan');
INSERT INTO clientes (region_id,apellido,createAt,email,nombre) VALUES (3,'Perez', '2022-11-09 00:00:00', 'juan@unicauca.edu.co', 'Juan');
